:queues:
  - default
  - mailers
  - [high_priority, 2]
  - [low_priority, 1]

:scheduler:
  :schedule:
    daily_watering_reminder:
      cron: "0 10 * * *"
      class: "DailyWateringReminderJob"
      queue: default
