:queues:
  - default
  - mailers
  - [high_priority, 2]
  - [low_priority, 1]

# config/sidekiq.yml
:scheduler:
  :schedule:
    watering_reminder:
      cron: "02 22 * * *"
      class: "DailyWateringReminderJob"
      queue: default
