name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up database
        run: |
          export DISABLE_SPRING=true
          bin/rails db:create db:schema:load
        env:
          RAILS_ENV: test

      - name: Run tests
        run: |
          echo "Running tests"
          bundle exec rspec
        env:
          RAILS_ENV: test
